// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pb/home/home.proto

package home

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	home "learngo/rpc/7-grpc-stream/pb/home"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Home struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Visitor *Home_Visitor  `protobuf:"bytes,2,opt,name=visitor,proto3" json:"visitor,omitempty"`
	Empty   *emptypb.Empty `protobuf:"bytes,3,opt,name=empty,proto3" json:"empty,omitempty"`
	// 这里Car和Home都在同一个package home下 所以可以不用包名前缀引用
	Car *home.Car `protobuf:"bytes,4,opt,name=car,proto3" json:"car,omitempty"`
}

func (x *Home) Reset() {
	*x = Home{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_home_home_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Home) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Home) ProtoMessage() {}

func (x *Home) ProtoReflect() protoreflect.Message {
	mi := &file_pb_home_home_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Home.ProtoReflect.Descriptor instead.
func (*Home) Descriptor() ([]byte, []int) {
	return file_pb_home_home_proto_rawDescGZIP(), []int{0}
}

func (x *Home) GetVisitor() *Home_Visitor {
	if x != nil {
		return x.Visitor
	}
	return nil
}

func (x *Home) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

func (x *Home) GetCar() *home.Car {
	if x != nil {
		return x.Car
	}
	return nil
}

// package.Person
type Home_Visitor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Home_Visitor) Reset() {
	*x = Home_Visitor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_home_home_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Home_Visitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Home_Visitor) ProtoMessage() {}

func (x *Home_Visitor) ProtoReflect() protoreflect.Message {
	mi := &file_pb_home_home_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Home_Visitor.ProtoReflect.Descriptor instead.
func (*Home_Visitor) Descriptor() ([]byte, []int) {
	return file_pb_home_home_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Home_Visitor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pb_home_home_proto protoreflect.FileDescriptor

var file_pb_home_home_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x6f, 0x6d, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x6d, 0x65,
	0x2f, 0x63, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x04, 0x48,
	0x6f, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x48, 0x6f, 0x6d, 0x65,
	0x2e, 0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x1b, 0x0a, 0x03, 0x63, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x68,
	0x6f, 0x6d, 0x65, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x03, 0x63, 0x61, 0x72, 0x1a, 0x1d, 0x0a, 0x07,
	0x56, 0x69, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x3b, 0x68, 0x6f, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_home_home_proto_rawDescOnce sync.Once
	file_pb_home_home_proto_rawDescData = file_pb_home_home_proto_rawDesc
)

func file_pb_home_home_proto_rawDescGZIP() []byte {
	file_pb_home_home_proto_rawDescOnce.Do(func() {
		file_pb_home_home_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_home_home_proto_rawDescData)
	})
	return file_pb_home_home_proto_rawDescData
}

var file_pb_home_home_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_home_home_proto_goTypes = []interface{}{
	(*Home)(nil),          // 0: home.Home
	(*Home_Visitor)(nil),  // 1: home.Home.Visitor
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
	(*home.Car)(nil),      // 3: home.Car
}
var file_pb_home_home_proto_depIdxs = []int32{
	1, // 0: home.Home.visitor:type_name -> home.Home.Visitor
	2, // 1: home.Home.empty:type_name -> google.protobuf.Empty
	3, // 2: home.Home.car:type_name -> home.Car
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_home_home_proto_init() }
func file_pb_home_home_proto_init() {
	if File_pb_home_home_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_home_home_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Home); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_home_home_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Home_Visitor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_home_home_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_home_home_proto_goTypes,
		DependencyIndexes: file_pb_home_home_proto_depIdxs,
		MessageInfos:      file_pb_home_home_proto_msgTypes,
	}.Build()
	File_pb_home_home_proto = out.File
	file_pb_home_home_proto_rawDesc = nil
	file_pb_home_home_proto_goTypes = nil
	file_pb_home_home_proto_depIdxs = nil
}
